name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
      
    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.app
    
    - name: Run Build
      env:
          ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
          KEY_SECRET: ${{ secrets.KEY_SECRET }}
      run: scripts/full-build.sh