name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.app
    
    - name: Create Keychain
      run: scripts/create-keychain.sh

    - name: Build App
      run: xcodebuild -scheme 'Feed Compass' -configuration Debug -allowProvisioningUpdates -showBuildTimingSummary

    - name: Delete Keychain
      run: scripts/remove-keychain.sh